steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/jakes-trading-bot', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/jakes-trading-bot']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'jakes-trading-bot'
    - '--image'
    - 'gcr.io/$PROJECT_ID/jakes-trading-bot'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY

images:
- 'gcr.io/$PROJECT_ID/jakes-trading-bot'

steps:
- name: python
  entrypoint: bash
  args:
    - -c
    - |
      pip install -r requirements.txt
      streamlit run app.py --server.port=8080

timeout: "900s"